### ISSUE TITLE
isHeadKvs

### ISSUE THREAD

**Issue by MathiasBartl** [MathiasBartl/Concurrent_Datastructures#28]
I got a problem witj determining, if a given Kvs object is the most senior, since Kvs Objects are in an one direction linked list, and I have difficulty understandin pointers in Haskell.
function has type:
isHeadKvs :: ConcurrentHashTable key val -> Kvs key val -> IO Bool
with definitions:
data ConcurrentHashTable key val = ConcurrentHashTable {	
		  kvs :: IORef(Kvs key val)
		  , timeOfLastResize :: IORef Time
}

data Kvs k v =   Kvs {
	newkvs :: IORef (Maybe ( Kvs k v))  
  	,slots :: Slots k v 
	, mask :: Mask
	, slotsCounter :: SlotsCounter
	, sizeCounter :: SizeCounter
	, _copyDone :: IORef CopyDone
	, copyIndex :: IORef CopyIndex  
}

**Comment by MathiasBartl** [comment]
Hi I am still at this problem, basically comparing and casing kvs objects.

**Comment by MathiasBartl** [comment]
Its all in the copyCheckAndPromote routine, I should probably rewrite it.

**Comment by MathiasBartl** [comment]
I think I got the problem now, every kvs has its distinct space of memory,
so I only need to compare if the pointer for the first slot of 2 kvses is identical.

**Comment by MathiasBartl** [comment]
idKvs ::Kvs key val -> Kvs key val -> Bool
idKvs a b = getHeadKey a == getHeadKey b
		where getHeadKey k = key $ V.head $ slots k					 
-- Each kvs has its unique area of memory

this should check if two kvs objects point to the same area of memory

**Comment by rrnewton** [comment]
Ah I see. So it was "physical equality" on these that was needed.  That seems like a nice cheap solution then.

**Comment by MathiasBartl** [comment]
Yes, I was a bit confused when I thought that I needed a pointer to an kvs, when the kvs actualy contains the pointer.
