### ISSUE TITLE
GHCI Debug issues

### ISSUE THREAD

**Issue by MathiasBartl** [MathiasBartl/Concurrent_Datastructures#33]
ser@user-Laptop:~/Gsoc/ConcurrentHashTable/gitHubRepo/Concurrent_Datastructures$ ghci
GHCi, version 7.8.3: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Prelude> :load tests/test2.hs
[1 of 2] Compiling Data.HashTable.Concurrent ( Data/HashTable/Concurrent.hs, interpreted )
[2 of 2] Compiling Main             ( tests/test2.hs, interpreted )
Ok, modules loaded: Main, Data.HashTable.Concurrent.
_Main> :break Data.HashTable.Concurrent 730
Breakpoint 0 activated at Data/HashTable/Concurrent.hs:730:22-78
*Main> :break Data.HashTable.Concurrent 754
Breakpoint 1 activated at Data/HashTable/Concurrent.hs:754:76-138
*Main> :break Data.HashTable.Concurrent 750
Breakpoint 2 activated at Data/HashTable/Concurrent.hs:750:86-98
*Main> main
Loading package array-0.5.0.0 ... linking ... done.
Loading package deepseq-1.3.0.2 ... linking ... done.
Loading package old-locale-1.0.0.6 ... linking ... done.
Loading package time-1.4.2 ... linking ... done.
Loading package containers-0.5.5.1 ... linking ... done.
Loading package bytestring-0.10.4.0 ... linking ... done.
Loading package transformers-0.4.1.0 ... linking ... done.
Loading package mtl-2.2.1 ... linking ... done.
Loading package random-1.0.1.1 ... linking ... done.
Loading package arithmoi-0.4.1.1 ... linking ... done.
Loading package pretty-1.1.1.1 ... linking ... done.
Loading package template-haskell ... linking ... done.
Loading package primitive-0.5.3.0 ... linking ... done.
Loading package tf-random-0.5 ... linking ... done.
Loading package QuickCheck-2.7.6 ... linking ... done.
Loading package unix-2.7.0.1 ... linking ... done.
Loading package ansi-terminal-0.6.1.1 ... linking ... done.
Loading package ansi-wl-pprint-0.6.7.1 ... linking ... done.
Loading package hostname-1.0 ... linking ... done.
Loading package regex-base-0.93.2 ... linking ... done.
Loading package regex-posix-0.95.2 ... linking ... done.
Loading package text-1.1.1.3 ... linking ... done.
Loading package xml-1.3.13 ... linking ... done.
Loading package test-framework-0.8.0.3 ... linking ... done.
Loading package either-unwrap-1.1 ... linking ... done.
Loading package hashable-1.2.2.0 ... linking ... done.
Loading package vector-0.10.11.0 ... linking ... done.
Loading package HUnit-1.2.5.2 ... linking ... done.
Loading package extensible-exceptions-0.1.1.4 ... linking ... done.
Loading package test-framework-hunit-0.3.0.1 ... linking ... done.
Loading package atomic-primops-0.6.0.5 ... linking ... done.
Stopped at Data/HashTable/Concurrent.hs:730:22-78
_result ::
  IO
    (Data.HashTable.Concurrent.Slot key1 val,
     Data.HashTable.Concurrent.ReprobeCounter) = _
key :: Data.HashTable.Concurrent.Key key1 = _
msk :: Data.HashTable.Concurrent.Mask = _
slts :: Data.HashTable.Concurrent.Slots key1 val = _
[Data/HashTable/Concurrent.hs:730:22-78] *Main> 
[_2_K_ I[g1nFor:itnegs tb1r:e a[kp[i9n1tm
F_a_i_l eIdgn[r0imn]g 
brEeRaRkOpRo:i n<t<
ti_m_e_o uItg>n>or
ing breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint

**2 KIg[o1rFin:gp ubtr:e a[kp[i9n2tm
O*K** [I0gmn]or
ing breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint

*\* 1IFgn:opruitn gt ob reeraakspeodi nstl
ot_:_ _[ Ig[n9o2rminOgK br[e0amk]po
int
*_\* Ignoring breakpoint

[2_K__ [I1gFno:rgientg:  b[rea[k9p2ominOtK
*0_m ]Ig
noring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint

**2 KIg[o1rFin:gp ubtrIefaAkbpsoeinntt:
 [** 9I2gmnoOrKing[ 0bmr]ea
kpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint

[2_K__ [I1gFno:rrienmgo vber:e a[kp[i9n2tm
O_K*_ [I0gmn]or
ing breakpoint
*_\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint

[2_K__ [I1gFno:rrienmgo vberKeeayk:p o[int[
92_m*_O KIg[o0rmi]ng
 breakpoint
*_\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint

[_2_K\* I[g1nFor:irnegp lbarceea:k p[oi[t9
2m*_O_K Ig[n0omr]in
g breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint

[2_K__ [I1gFno:rrienpgl abcreeTaekspto:i n[t
[_9_2_m IOgKnor[i0nmg] b
reakpoint
**\* Ignoring breakpoint

**2 KIg[o1rFin:gc lberaera:k p[oi[t9
2m**O_K Ig[n0omr]in
g breakpoint
*_\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint

[2_K__ [I1gFno:riisnEgm pbtrye:a k[poi[n9t2
m_O_K_ I[g0nmo]ri
ng breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint

[2_K__ [I1gFno:rsiinzge :b r[eak[p9o2imntO
K__0 mI]gn
oring breakpoint
*_\* Ignoring breakpoint

[_2_K\* I[g1nFor:icnogn tbarienaskVpaoliunet:
 [*\* 9I2gmnoOrKing[ 0bmr]ea
kpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint

**1 FIg:ncoornitnagi nbsrKeeayk:p o[int[
92*m**O KIg[o0rmi]ng
 b
rea[k2pKoi[t1
F_:_n_e wICgonnocruirnrge nbtrHeaaskhpToaibnlte
Hi_n_t_:  I[gn[r9i2nmg ObKrea[k0pmo]in
t
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint

*_1 FIg:nuonrniencge sbsraerayk_pkoeiyn_tw
ri_t_e_s :I g[nor[i9n2gm bOrKeak[p0omi]nt

*\* 2IKgn[r1iFng: gberteNaukmpboeirnOtf
OngoingResizes: [OK]
:getLengthsOfVectors: [OK]
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**:_g eItgSnloortisnCgo ubnrteearksp:o i[nt
[9_2_m_ OIKgn[r0imn]g 
br
eak[p2oKint[
1F**:_g eItgRneoprrionbge Cboruenatk:p o[int[
92_m*_O KIg[o0rmi]ng
 breakpoint
*_\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
**\* Ignoring breakpoint
:resize: [Failed]
ERROR: <<timeout>>

```
     Test Cases   Total       
```

 Passed  19           19  
 Failed  2            2  
 Total   21           21

**Comment by MathiasBartl** [comment]
Thats probably because the framework launches the testcases in parallel.

**Comment by rrnewton** [comment]
On the command line at least, test-framework can take an argument to do them sequentially.
